#配置Tomcat端口、url的编码
server:
  port: 10089
  tomcat:
    uri-encoding: utf-8
  #配置serverlet的路径
  servlet:
    context-path: /farmService
    #-path: *.action

#视图解析器
spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/farmservice?useUnicode=true&characterEncoding=utf8
      username: root
      password: 575534
  dubbo:
      application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
        name: farm-certify
      registry:                 #注册中心配置，用于配置连接注册中心相关信息。
        address: zookeeper://192.168.1.180:2181
      protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
        name: dubbo
        port: 20881     #服务调用端口

mybatis:
  type-aliases-package: edu.zhku.pojo
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    edu.zhku.mapper : debug




